// <auto-generated />
using System;
using CleanArchitecture.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Infrastructure.Migrations
{
    [DbContext(typeof(AfiliacionesDbContext))]
    [Migration("20230209124436_TipoDocumento")]
    partial class TipoDocumento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CleanArchitecture.Domain.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Afiliado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AFIPActividadPrincipal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AFIPApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("AFIPCUIL")
                        .HasColumnType("bigint");

                    b.Property<long?>("AFIPClaveInactivaAsociada")
                        .HasColumnType("bigint");

                    b.Property<string>("AFIPDomicilioCalle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AFIPDomicilioCodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("AFIPDomicilioDatoAdicional")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPDomicilioDepto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPDomicilioDireccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AFIPDomicilioEstado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AFIPDomicilioIdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("AFIPDomicilioLocalidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPDomicilioManzana")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AFIPDomicilioNumero")
                        .HasColumnType("int");

                    b.Property<string>("AFIPDomicilioPiso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPDomicilioProvincia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPDomicilioSector")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPDomicilioTipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPDomicilioTipoDatoAdicional")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPDomicilioTorre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPEstadoClave")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("AFIPFechaContratoSocial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AFIPFechaFallecimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AFIPFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("AFIPFormaJuridica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AFIPIdActividadPrincipal")
                        .HasColumnType("int");

                    b.Property<int?>("AFIPMesCierre")
                        .HasColumnType("int");

                    b.Property<string>("AFIPNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AFIPNumeroDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("AFIPPeriodoActividadPrincipal")
                        .HasColumnType("int");

                    b.Property<string>("AFIPRazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AFIPTipoClave")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPTipoDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AFIPTipoPersona")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<long>("CUIL")
                        .HasColumnType("bigint");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DireccionReal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Documento")
                        .HasColumnType("bigint");

                    b.Property<int>("EmpresaId")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoSolicitudId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NacionalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NroAfiliado")
                        .HasColumnType("int");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int");

                    b.Property<int>("SeccionalId")
                        .HasColumnType("int");

                    b.Property<int>("Secuencia")
                        .HasColumnType("int");

                    b.Property<int>("SexoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("CUIL")
                        .IsUnique();

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("EstadoSolicitudId");

                    b.HasIndex("NacionalidadId");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("SeccionalId");

                    b.HasIndex("SexoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Afiliados");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.DDJJUatre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Actividad")
                        .HasColumnType("float");

                    b.Property<double>("Ajuste")
                        .HasColumnType("float");

                    b.Property<int>("Banco")
                        .HasColumnType("int");

                    b.Property<double>("CUIL")
                        .HasColumnType("float");

                    b.Property<int>("CUILCondicion")
                        .HasColumnType("int");

                    b.Property<int>("CUILSituacion")
                        .HasColumnType("int");

                    b.Property<double>("CUIT")
                        .HasColumnType("float");

                    b.Property<int>("DiasTrabajados")
                        .HasColumnType("int");

                    b.Property<int>("GrupoFamiliar")
                        .HasColumnType("int");

                    b.Property<int>("HsExtrasCantidad")
                        .HasColumnType("int");

                    b.Property<double>("HsExtrasImporte")
                        .HasColumnType("float");

                    b.Property<int>("Modalidad")
                        .HasColumnType("int");

                    b.Property<int>("NoGrupoFamiliar")
                        .HasColumnType("int");

                    b.Property<int>("OSDestino")
                        .HasColumnType("int");

                    b.Property<double>("ObligacionNro")
                        .HasColumnType("float");

                    b.Property<int>("ObligacionSecuencia")
                        .HasColumnType("int");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<DateTime>("PresentacionFecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProcesoFecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rectificativa")
                        .HasColumnType("int");

                    b.Property<double>("Reduccion")
                        .HasColumnType("float");

                    b.Property<double>("RemuneracionImponible")
                        .HasColumnType("float");

                    b.Property<double>("Renatea")
                        .HasColumnType("float");

                    b.Property<double>("SAC")
                        .HasColumnType("float");

                    b.Property<int>("SiniestroCod")
                        .HasColumnType("int");

                    b.Property<double>("Vacaciones")
                        .HasColumnType("float");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("VersionRelease")
                        .HasColumnType("int");

                    b.Property<int>("Zona")
                        .HasColumnType("int");

                    b.Property<double>("ZonaDesfavorable")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DDJJUatre", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ActividadPrincipalDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActividadPrincipalId")
                        .HasColumnType("int");

                    b.Property<int?>("ActividadPrincipalPeriodo")
                        .HasColumnType("int");

                    b.Property<double>("CUIT")
                        .HasColumnType("float");

                    b.Property<byte?>("CierreMes")
                        .HasColumnType("tinyint");

                    b.Property<string>("ClaveEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ClaveInactivaAsociada")
                        .HasColumnType("float");

                    b.Property<string>("ClaveTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContratoSocialFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("DomicilioCPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioCalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DomicilioCodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("DomicilioDatoAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioDatoAdicionalTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioDpto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioManzana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DomicilioNumero")
                        .HasColumnType("int");

                    b.Property<string>("DomicilioPiso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DomicilioProvinciasId")
                        .HasColumnType("int");

                    b.Property<string>("DomicilioSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicilioTorre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int")
                        .HasColumnName("DomicilioLocalidadesId");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.ToTable("Empresa", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("CleanArchitecture.Domain.EstadoCivil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EstadosCiviles");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EstadosSolicitudes");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CP")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Nacionalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Nacionalidades");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProvinciaAFIP")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Seccional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Seccionales");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.SeccionalLocalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<int>("SeccionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.HasIndex("SeccionalId");

                    b.ToTable("SeccionalesLocalidades");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sexos");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumentos");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Afiliado", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.EstadoCivil", "EstadoCivil")
                        .WithMany()
                        .HasForeignKey("EstadoCivilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany()
                        .HasForeignKey("EstadoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Nacionalidad", "Nacionalidad")
                        .WithMany()
                        .HasForeignKey("NacionalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Seccional", "Seccional")
                        .WithMany()
                        .HasForeignKey("SeccionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("EstadoCivil");

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("Nacionalidad");

                    b.Navigation("Provincia");

                    b.Navigation("Puesto");

                    b.Navigation("Seccional");

                    b.Navigation("Sexo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Empresa", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Localidad", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.SeccionalLocalidad", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Localidad", "Localidad")
                        .WithMany("SeccionalLocalidad")
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Seccional", "Seccional")
                        .WithMany("SeccionalLocalidad")
                        .HasForeignKey("SeccionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");

                    b.Navigation("Seccional");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Localidad", b =>
                {
                    b.Navigation("SeccionalLocalidad");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Seccional", b =>
                {
                    b.Navigation("SeccionalLocalidad");
                });
#pragma warning restore 612, 618
        }
    }
}
