// <auto-generated />
using System;
using CleanArchitecture.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Infrastructure.Migrations
{
    [DbContext(typeof(AfiliacionesDbContext))]
    partial class AfiliacionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CleanArchitecture.Domain.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EstadosSolicitud");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Aprobado"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Rechazado"
                        });
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Padron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AFIPActividadPrincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AFIPCUIL")
                        .HasColumnType("bigint");

                    b.Property<long?>("AFIPClaveInactivaAsociada")
                        .HasColumnType("bigint");

                    b.Property<string>("AFIPDomicilioCalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AFIPDomicilioCodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("AFIPDomicilioDatoAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioDepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AFIPDomicilioIdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("AFIPDomicilioLocalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioManzana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AFIPDomicilioNumero")
                        .HasColumnType("int");

                    b.Property<string>("AFIPDomicilioPiso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioProvincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioTipoDatoAdicional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPDomicilioTorre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPEstadoClave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AFIPFechaContratoSocial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AFIPFechaFallecimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AFIPFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("AFIPFormaJuridica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AFIPIdActividadPrincipal")
                        .HasColumnType("int");

                    b.Property<int?>("AFIPMesCierre")
                        .HasColumnType("int");

                    b.Property<string>("AFIPNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AFIPNumeroDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("AFIPPeriodoActividadPrincipal")
                        .HasColumnType("int");

                    b.Property<string>("AFIPRazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPTipoClave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPTipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AFIPTipoPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<int>("Afiliado")
                        .HasColumnType("int");

                    b.Property<long>("CUIL")
                        .HasColumnType("bigint");

                    b.Property<long>("CUIT")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DNI")
                        .HasColumnType("bigint");

                    b.Property<int>("EstadoSolicitudId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAnexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int");

                    b.Property<int>("SeccionalId")
                        .HasColumnType("int");

                    b.Property<int>("Secuencia")
                        .HasColumnType("int");

                    b.Property<int>("SexoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("EstadoSolicitudId");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("SeccionalId");

                    b.HasIndex("SexoId");

                    b.ToTable("Padrones");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Seccional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Seccionales");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sexos");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Localidad", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Padron", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany()
                        .HasForeignKey("EstadoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Seccional", "Seccional")
                        .WithMany()
                        .HasForeignKey("SeccionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitecture.Domain.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("Provincia");

                    b.Navigation("Puesto");

                    b.Navigation("Seccional");

                    b.Navigation("Sexo");
                });
#pragma warning restore 612, 618
        }
    }
}
